name: CI

on:
  push:
    branches:
      - master
      - develop
      - feature-*
      - release-*
  pull_request:
    branches:
      - master
      - develop
      - feature-*
      - release-*

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Create directories
      run: |
        mkdir -p tests/test_reports

    - name: Run tests with coverage
      run: |
        source venv/bin/activate
        python -m pytest

    - name: Upload coverage to SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.python.version=3
          -Dsonar.branch.name=${{ github.ref_name }}
          -Dsonar.sources=src/
          -Dsonar.python.coverage.reportPaths=tests/test_reports/coverage.xml
